name: Emoji Check

on: [push, workflow_dispatch, pull_request]

jobs:
  check-emoji:
    runs-on: macos-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install emoji-regex

      - name: Check PR title for emoji
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target' || github.event_name == 'push'
        uses: actions/github-script@v7
        with:
          script: |
            const emojiRegex = require('emoji-regex');
            const regex = emojiRegex();
            
            if (context.eventName === 'push') {
              // For push events, check the commit message
              const message = context.payload.head_commit.message.split('\n')[0];
              if (!regex.test(message)) {
                core.setFailed(`❌ Push commit must include an emoji! Current message: "${message}"

                Examples of good commit messages:
                ✨ Add new feature
                🐛 Fix login bug
                🎨 Update styles
                
                Suggested emojis:
                ✨ New feature    🐛 Bug fix      🎨 UI/Style
                🚀 Performance   🧱 Infrastructure
                ♻️ Refactor      🔧 Configuration
                📝 Documentation 🔒 Security
                🧪 Testing       ⚡️ Improvement`);
              } else {
                console.log(`✅ Push commit "${message}" contains an emoji`);
              }
            } else {
              // For PR events, check the title
              const title = context.payload.pull_request.title;
              if (!regex.test(title)) {
                core.setFailed(`❌ PR title must include an emoji! Current title: "${title}"

                Examples of good PR titles:
                ✨ Add new feature
                🐛 Fix login bug
                🎨 Update styles
                
                Suggested emojis:
                ✨ New feature    🐛 Bug fix      🎨 UI/Style
                🚀 Performance   🧱 Infrastructure
                ♻️ Refactor      🔧 Configuration
                📝 Documentation 🔒 Security
                🧪 Testing       ⚡️ Improvement`);
              } else {
                console.log(`✅ PR title "${title}" contains an emoji`);
              }
            }

      - name: Check commit messages
        uses: actions/github-script@v7
        with:
          script: |
            const emojiRegex = require('emoji-regex');
            const regex = emojiRegex();
            
            let commits;
            if (context.eventName === 'push') {
              // For push events, check the pushed commits
              commits = context.payload.commits.map(commit => ({
                commit: { message: commit.message },
                sha: commit.id
              }));
            } else {
              // For PR events, get commits through API
              const prCommits = await github.rest.pulls.listCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number
              });
              commits = prCommits.data;
            }
            
            let hasInvalidCommit = false;
            for (const commit of commits) {
              const message = commit.commit.message.split('\n')[0];
              if (!regex.test(message)) {
                console.log(`❌ Commit ${commit.sha.substring(0, 7)} missing emoji: "${message}"`);
                hasInvalidCommit = true;
              }
            }
            
            if (hasInvalidCommit) {
              core.setFailed(`Some commit messages are missing emojis. Please add appropriate emojis to all commit messages.

              Examples:
              ✨ Add new feature
              🐛 Fix login bug
              🎨 Update styles`);
            } 